fix(docgen): use real prop name instead of v-model
vue-styleguidist/vue-styleguidist pull request #1056
Opened 2021-02-03 10:19 UTC by supachailllpay

## What?

This PR will change the behavior of `propHandler` to return `propertyName` instead of string `v-model` in case of model prop.

https://github.com/vue-styleguidist/vue-styleguidist/blob/70cbb593cbbb6f94f300c5c1ddad69c4d38e81e7/packages/vue-docgen-api/src/script-handlers/propHandler.ts#L80-L82

Fix #1039

## Why?

I ran into a problem when using the storybook with vue which uses this package to automatically generate [ArgTypes](https://storybook.js.org/docs/vue/api/argtypes#automatic-argtype-inference).

My checkbox component

```html
<script>
  export default {
    model: {
      prop: 'checked',
      event: 'change'
    },

    props: {
      label: String,
      checked: Boolean
    }
  }
</script>
```

and the output is 

```javascript
{
  v-model: { name: 'v-model', type: { name: 'boolean' }, ... },
  label: { name: 'label', type: { name: 'string' }, ... }
}
```

and then bind it to component

```javascript
const Template = (args, { argTypes }) => ({
  components: { Checkbox },
  props: Object.keys(argTypes),
  template: '<Checkbox v-bind="$props" />'
})
```

As you can see, the storybook assumes that the output from this api will return the prop name like `label` but in the case of model prop this api return `v-model` which is not an actual prop but it is a directive.

So I think we should return the real prop name instead of string `v-model` and use different field to indicate that this prop is a model prop.

As in this comment https://github.com/vue-styleguidist/vue-styleguidist/issues/1039#issuecomment-757972226.

## How?

For now I only change the code to return `propertyName` whether that prop is model prop or not. Since I'm really new here, I'm not sure what fields to use to specify this is a prop model, or even if I should include it in this PR.

And this looks like a breaking change, not sure if it's possible. I would like to hear your feedback.

This is my first time here, sorry for the mistake. Thank you for your time.

2021-02-03 10:49 UTC, supachailllpay commented on packages/vue-docgen-api/tests/components/functional/__snapshots__/InputWrapper-functional.test.ts.snap
> -      "name": "v-model",
In this file I only change the name from `v-model` to `value` and remove 1 prop.

original

https://github.com/vue-styleguidist/vue-styleguidist/blob/70cbb593cbbb6f94f300c5c1ddad69c4d38e81e7/packages/vue-docgen-api/tests/components/functional/__snapshots__/InputWrapper-functional.test.ts.snap#L63-L67

Other changes caused by reordering

2021-02-03 10:49 UTC, supachailllpay commented on packages/vue-docgen-api/src/Documentation.ts
> +		return this.getDescriptor(propName, this.propsMap, () => ({
If I understand correctly, this change will not have any effect. Since at first `vModelDescriptor` will be undefined and after when it has value it will always `vModelDescriptor.name === propName`.

2021-02-04 18:13 UTC, elevatebart commented
This looks like a storybook bug.
It also looks like a breaking change for vue-styleguidist. 
Would you mind logging a ticket on SB for it?

2021-02-04 18:15 UTC, elevatebart commented
My apologies for my previous comment, I have been a bit busy recently and forgot our conversation.
I will review the changes as soon as I can.

2021-02-08 19:20 UTC, elevatebart requested changes
Here, the notion of v-model has entirely disappeared. 
It is useful information to have.
I would prefer that instead of obliterating it, we make it available as a separate flag.

Vue 3 components can have multiple v-models with scoped events so we should have the v-models as a separate group in the output object. 

Like `props`, `events`, `slots` and `methods`, we should add a `model` entry to the top level object.
This entry would contain an array of vModels (each being a combo prop/event).

```js
const obj = {
  props: [],
  events: []
  model: [
   {
      prop:'value',
      event: 'change'
    },
    ...
  ]
}
```

What do you think of this model?

2021-02-08 19:20 UTC, elevatebart commented on packages/vue-docgen-api/src/Documentation.ts
> +		return this.getDescriptor(propName, this.propsMap, () => ({
It can have an effect if the prop we are analyzing already exists. 
Id-est, if the prop was defined in a mixin or extends before you came to this specific v-model.

2021-02-10 01:28 UTC, supachailllpay commented
You mean something like this?

```typescript
export interface VModelDescriptor extends Descriptor {
  prop: string;
  event?: string;
}

export interface ComponentDoc {
  displayName: string;
  exportName: string;
  description?: string;
  props?: PropDescriptor[];
  methods?: MethodDescriptor[];
  slots?: SlotDescriptor[];
  events?: EventDescriptor[];
  vModels?: VModelDescriptor[];
  tags?: {
    [key: string]: BlockTag[];
  };
  docsBlocks?: string[];
  [key: string]: any;
}
```

I think one downside of this model is when I iterate over `props` and I want to know if this prop is a v-model. I have to lookup to `vModels` to find if it contains this prop name.

But since v-model is involved to both prop and event, which means that if we provide this v-model information inside prop, when I iterate over `events` I will face the similar problem anyway (not sure this should be considered as a use case).

---

And from your previous comment that you mentioned the behavior when mixin or extends is defined.

https://github.com/vue-styleguidist/vue-styleguidist/blob/82fac7ade7b295915aa97db39ac30554c3af80ca/packages/vue-docgen-api/src/Documentation.ts#L73-L80

I guess this code is meant to fix these cases:

- The model is defined only in mixin
- The model is defined only in component

But it seems that it fails in both cases. In the first case, the first time it will call `getPropDescriptor` with string v-model and the second time it will call with the actual prop name not v-model so it return the new descriptor. And vice versa for the second case.

The result contains both v-model and the actual prop which they should be merged.

2021-06-02 15:43 UTC, closed without merging