add support for new defineEmits syntax in Vue 3.3
vue-styleguidist/vue-styleguidist pull request #1616
Opened 2023-10-20 18:18 UTC by pscheede

Vue 3.3 added support for a new syntax when using `defineEmits()` in a `<script setup>` tag.

Instead of using call signartures like this:

```ts
defineEmits<{
  (e: input, value: string): void,
}>()
```

a property based type like this can be used:

```ts
defineEmits<{
  input: [value: string],
}>()
```

`vue-docgen-api` did not yet recognize this new possible syntax, so all events from the script tag were missing from the generated result.

2023-10-20 18:25 UTC, pscheede commented
I've just taken a quick look at the open issues and I believe this would fix #1598

2023-10-21 08:25 UTC, elevatebart requested changes
I think there is a small hiccup here. Can you explain or fix?

2023-10-21 08:25 UTC, elevatebart commented on packages/vue-docgen-api/tests/components/setup-new-emit-syntax/setup-new-emit-syntax.test.ts
> +				        "TSTupleType",
I am not sure this is the type you would expect here

2023-10-21 09:02 UTC, pscheede commented on packages/vue-docgen-api/tests/components/setup-new-emit-syntax/setup-new-emit-syntax.test.ts
> +				        "TSTupleType",
@elevatebart 
I am unsure about this type as well, but I wanted to touch as little as possible, especially the `getTypeFromAnnotation()` function.

It currently comes from the fact that each signature of an emit is now typed with a tuple:

```ts
type Emits = {
  input: [value: string],
};
```

But now that I think about it, I could try extracting the type of the first parameter of the emit, like I believe it is done for the "old" call signature syntax.

This would mean that for emits with multiple parameters you would only get the type of the first parameter, but I suppose that's better than `TsTupleType`. Or do you have an idea or more insight how the returned value could include the types for all parameters?

2023-10-23 08:20 UTC, pscheede commented on packages/vue-docgen-api/tests/components/setup-syntax/Progress.vue
> +	(event: 'eventWithTuplePayload', arg: [number, string]): void
Before my changes the old event syntax was parsed to `{ names: [ "TSTupleType" ] }` for this case of a tuple as first argument to an event.

Now - as you can see in the snapshot - it is parsed differently.

Would this be considered a breaking change? If so, I will add a flag, that tuples are  only recursively parsed for the new syntax. Then all existing usages of `getTypeFromAnnotation` will remain the same.

2023-10-25 12:55 UTC, elevatebart commented on packages/vue-docgen-api/tests/components/setup-syntax/Progress.vue
> +	(event: 'eventWithTuplePayload', arg: [number, string]): void
I think you should keep it simple. The beaking change would not be a common use case as tuples are a new thing in TS. 

Keep the code as readable as possible and I will merge.

2023-10-25 12:58 UTC, elevatebart approved these changes

2023-10-25 14:04 UTC, merged